# Generated by Django 5.2.14 on 2026-05-27 03:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id_muestra', models.AutoField(primary_key=True, serialize=False)),
                ('salinidad', models.FloatField()),
                ('humedad', models.FloatField()),
                ('conductividad', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('ubicacion_exacta', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('fecha_hora_captura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoCritico',
            fields=[
                ('id_punto_critico', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ej: Hundimiento por humedad', max_length=100)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_tierra', models.CharField(choices=[('GREEN', 'Green'), ('FAIRWAY', 'Fairway')], max_length=20)),
                ('numero_de_hoyo', models.IntegerField()),
                ('poligono', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('AGRO', 'Agrónoma'), ('CANCHERO', 'Canchero')], max_length=20)),
                ('ruta_foto', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_archivo', models.URLField()),
                ('fecha_hora_subida', models.DateTimeField(auto_now_add=True)),
                ('id_muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.muestra')),
            ],
        ),
        migrations.AddField(
            model_name='muestra',
            name='id_punto_critico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras', to='core.puntocritico'),
        ),
        migrations.AddField(
            model_name='puntocritico',
            name='id_seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_criticos', to='core.seccion'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='id_seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='core.seccion'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='rut_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='muestras_tomadas', to='core.usuario'),
        ),
    ]
