# Generated by Django 5.2.14 on 2026-06-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='conductividad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='humedad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='salinidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
