# Generated by Django 5.2.14 on 2026-06-08 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_muestra_conductividad_alter_muestra_humedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='humedad',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
