# Generated by Django 5.2.14 on 2026-06-23 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_muestra_humedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]{8}[0-9kK]$', 'El RUT debe tener exactamente 9 caracteres (8 números y un dígito final o k).')]),
        ),
    ]
