# Generated by Django 5.2.14 on 2026-06-23 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_muestra_humedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[\\d\\.\\-]{8,13}$', 'El RUT no es válido. Debe tener hasta 13 caracteres.')]),
        ),
    ]
