# Generated by Django 5.2.14 on 2026-06-29 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usuario_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMuestra',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición')], max_length=20)),
                ('cambios', models.JSONField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.muestra')),
                ('rut_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_muestras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
